// --------------------------------------
// Generated by Verilog Compiler
// --------------------------------------
module Inception_v4_top;

localparam CLK_PERIOD = 1.0;

// Interconnections
reg clk, rst, enable;
wire input_layer_valid, input_layer_rdy;
wire [95:0] input_layer_data;
wire [31:0] input_layer_data_2d [2:0];
wire output_layer_valid, output_layer_rdy;
wire [31999:0] output_layer_data;
wire [31:0] output_layer_data_2d [999:0];
wire stop_sim;
genvar i;

// testbench
testbench #(
	.Nin (3),
	.Nout (1000),
	.BIT_WIDTH (32),
	.INPUT_SPATIAL_DIM (89401),
	.FRAME_SIZE (1)
) testbench_inst (
	.clk (clk),
	.rst (rst),
	.input_layer_rdy (input_layer_rdy),
	.input_layer_valid (input_layer_valid),
	.input_layer_data (input_layer_data),
	.output_layer_rdy (output_layer_rdy),
	.output_layer_valid (output_layer_valid),
	.output_layer_data (output_layer_data),
	.stop_sim (stop_sim)
);
// UUT
Inception_v4 uut (
	.clk (clk),
	.rst (rst),
	.enable (enable),
	.input_layer_valid (input_layer_valid),
	.input_layer_rdy (input_layer_rdy),
	.input_layer_data (input_layer_data),
	.output_layer_valid (output_layer_valid),
	.output_layer_rdy (output_layer_rdy),
	.output_layer_data (output_layer_data)
);
// 2D data unpack
generate
for (i = 0; i < 3; i = i + 1) begin: input_data_unpack
	assign input_layer_data_2d[i] = input_layer_data[i*32+:32];
end
for (i = 0; i < 1000; i = i + 1) begin: output_layer_unpack
	assign output_layer_data_2d[i] = output_layer_data[i*32+:32];
end
endgenerate

// clock generation
initial begin
	clk = 1'b0;
	forever #(CLK_PERIOD/2.0) clk = ~clk;
end
// rst & enable
initial begin
	rst = 1'b1;
	enable = 1'b0;
	#(CLK_PERIOD*5);
	@(negedge clk);
	rst = 1'b0;
	enable = 1'b1;
end

// record the max buffer depth to the file
integer fp;
initial begin
	fp = $fopen("buffer_depth.list", "w");
	wait(stop_sim == 1'b1);
	$fdisplay(fp, "conv1_3x3_s2_inter_channel_buffer %d", uut.conv1_3x3_s2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "conv2_3x3_s1_inter_channel_buffer %d", uut.conv2_3x3_s1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "conv3_3x3_s1_inter_channel_buffer %d", uut.conv3_3x3_s1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem1_3x3_s2_inter_channel_buffer %d", uut.inception_stem1_3x3_s2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem1_pool_inter_channel_buffer %d", uut.inception_stem1_pool_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem1_inception_channel_buffer_0 %d", uut.inception_stem1_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem1_inception_channel_buffer_1 %d", uut.inception_stem1_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem2_3x3_reduce_inter_channel_buffer %d", uut.inception_stem2_3x3_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem2_3x3_inter_channel_buffer %d", uut.inception_stem2_3x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem2_7x1_reduce_inter_channel_buffer %d", uut.inception_stem2_7x1_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem2_7x1_inter_channel_buffer %d", uut.inception_stem2_7x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem2_1x7_inter_channel_buffer %d", uut.inception_stem2_1x7_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem2_3x3_2_inter_channel_buffer %d", uut.inception_stem2_3x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem2_inception_channel_buffer_0 %d", uut.inception_stem2_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem2_inception_channel_buffer_1 %d", uut.inception_stem2_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem3_3x3_s2_inter_channel_buffer %d", uut.inception_stem3_3x3_s2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem3_pool_inter_channel_buffer %d", uut.inception_stem3_pool_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem3_inception_channel_buffer_0 %d", uut.inception_stem3_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_stem3_inception_channel_buffer_1 %d", uut.inception_stem3_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_pool_ave_inter_channel_buffer %d", uut.inception_a1_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_1x1_inter_channel_buffer %d", uut.inception_a1_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_1x1_2_inter_channel_buffer %d", uut.inception_a1_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_3x3_reduce_inter_channel_buffer %d", uut.inception_a1_3x3_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_3x3_inter_channel_buffer %d", uut.inception_a1_3x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_3x3_2_reduce_inter_channel_buffer %d", uut.inception_a1_3x3_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_3x3_2_inter_channel_buffer %d", uut.inception_a1_3x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_3x3_3_inter_channel_buffer %d", uut.inception_a1_3x3_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_concat_inception_channel_buffer_0 %d", uut.inception_a1_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_concat_inception_channel_buffer_1 %d", uut.inception_a1_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_concat_inception_channel_buffer_2 %d", uut.inception_a1_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a1_concat_inception_channel_buffer_3 %d", uut.inception_a1_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_pool_ave_inter_channel_buffer %d", uut.inception_a2_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_1x1_inter_channel_buffer %d", uut.inception_a2_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_1x1_2_inter_channel_buffer %d", uut.inception_a2_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_3x3_reduce_inter_channel_buffer %d", uut.inception_a2_3x3_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_3x3_inter_channel_buffer %d", uut.inception_a2_3x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_3x3_2_reduce_inter_channel_buffer %d", uut.inception_a2_3x3_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_3x3_2_inter_channel_buffer %d", uut.inception_a2_3x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_3x3_3_inter_channel_buffer %d", uut.inception_a2_3x3_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_concat_inception_channel_buffer_0 %d", uut.inception_a2_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_concat_inception_channel_buffer_1 %d", uut.inception_a2_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_concat_inception_channel_buffer_2 %d", uut.inception_a2_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a2_concat_inception_channel_buffer_3 %d", uut.inception_a2_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_pool_ave_inter_channel_buffer %d", uut.inception_a3_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_1x1_inter_channel_buffer %d", uut.inception_a3_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_1x1_2_inter_channel_buffer %d", uut.inception_a3_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_3x3_reduce_inter_channel_buffer %d", uut.inception_a3_3x3_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_3x3_inter_channel_buffer %d", uut.inception_a3_3x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_3x3_2_reduce_inter_channel_buffer %d", uut.inception_a3_3x3_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_3x3_2_inter_channel_buffer %d", uut.inception_a3_3x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_3x3_3_inter_channel_buffer %d", uut.inception_a3_3x3_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_concat_inception_channel_buffer_0 %d", uut.inception_a3_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_concat_inception_channel_buffer_1 %d", uut.inception_a3_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_concat_inception_channel_buffer_2 %d", uut.inception_a3_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a3_concat_inception_channel_buffer_3 %d", uut.inception_a3_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_pool_ave_inter_channel_buffer %d", uut.inception_a4_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_1x1_inter_channel_buffer %d", uut.inception_a4_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_1x1_2_inter_channel_buffer %d", uut.inception_a4_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_3x3_reduce_inter_channel_buffer %d", uut.inception_a4_3x3_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_3x3_inter_channel_buffer %d", uut.inception_a4_3x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_3x3_2_reduce_inter_channel_buffer %d", uut.inception_a4_3x3_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_3x3_2_inter_channel_buffer %d", uut.inception_a4_3x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_3x3_3_inter_channel_buffer %d", uut.inception_a4_3x3_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_concat_inception_channel_buffer_0 %d", uut.inception_a4_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_concat_inception_channel_buffer_1 %d", uut.inception_a4_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_concat_inception_channel_buffer_2 %d", uut.inception_a4_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_a4_concat_inception_channel_buffer_3 %d", uut.inception_a4_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_a_pool_inter_channel_buffer %d", uut.reduction_a_pool_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_a_3x3_inter_channel_buffer %d", uut.reduction_a_3x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_a_3x3_2_reduce_inter_channel_buffer %d", uut.reduction_a_3x3_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_a_3x3_2_inter_channel_buffer %d", uut.reduction_a_3x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_a_3x3_3_inter_channel_buffer %d", uut.reduction_a_3x3_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_a_concat_inception_channel_buffer_0 %d", uut.reduction_a_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_a_concat_inception_channel_buffer_1 %d", uut.reduction_a_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_a_concat_inception_channel_buffer_2 %d", uut.reduction_a_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_pool_ave_inter_channel_buffer %d", uut.inception_b1_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_1x1_inter_channel_buffer %d", uut.inception_b1_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_1x1_2_inter_channel_buffer %d", uut.inception_b1_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_1x7_reduce_inter_channel_buffer %d", uut.inception_b1_1x7_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_1x7_inter_channel_buffer %d", uut.inception_b1_1x7_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_7x1_inter_channel_buffer %d", uut.inception_b1_7x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_1x7_2_reduce_inter_channel_buffer %d", uut.inception_b1_1x7_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_1x7_2_inter_channel_buffer %d", uut.inception_b1_1x7_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_7x1_2_inter_channel_buffer %d", uut.inception_b1_7x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_1x7_3_inter_channel_buffer %d", uut.inception_b1_1x7_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_7x1_3_inter_channel_buffer %d", uut.inception_b1_7x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_concat_inception_channel_buffer_0 %d", uut.inception_b1_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_concat_inception_channel_buffer_1 %d", uut.inception_b1_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_concat_inception_channel_buffer_2 %d", uut.inception_b1_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b1_concat_inception_channel_buffer_3 %d", uut.inception_b1_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_pool_ave_inter_channel_buffer %d", uut.inception_b2_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_1x1_inter_channel_buffer %d", uut.inception_b2_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_1x1_2_inter_channel_buffer %d", uut.inception_b2_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_1x7_reduce_inter_channel_buffer %d", uut.inception_b2_1x7_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_1x7_inter_channel_buffer %d", uut.inception_b2_1x7_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_7x1_inter_channel_buffer %d", uut.inception_b2_7x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_1x7_2_reduce_inter_channel_buffer %d", uut.inception_b2_1x7_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_1x7_2_inter_channel_buffer %d", uut.inception_b2_1x7_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_7x1_2_inter_channel_buffer %d", uut.inception_b2_7x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_1x7_3_inter_channel_buffer %d", uut.inception_b2_1x7_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_7x1_3_inter_channel_buffer %d", uut.inception_b2_7x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_concat_inception_channel_buffer_0 %d", uut.inception_b2_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_concat_inception_channel_buffer_1 %d", uut.inception_b2_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_concat_inception_channel_buffer_2 %d", uut.inception_b2_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b2_concat_inception_channel_buffer_3 %d", uut.inception_b2_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_pool_ave_inter_channel_buffer %d", uut.inception_b3_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_1x1_inter_channel_buffer %d", uut.inception_b3_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_1x1_2_inter_channel_buffer %d", uut.inception_b3_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_1x7_reduce_inter_channel_buffer %d", uut.inception_b3_1x7_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_1x7_inter_channel_buffer %d", uut.inception_b3_1x7_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_7x1_inter_channel_buffer %d", uut.inception_b3_7x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_1x7_2_reduce_inter_channel_buffer %d", uut.inception_b3_1x7_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_1x7_2_inter_channel_buffer %d", uut.inception_b3_1x7_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_7x1_2_inter_channel_buffer %d", uut.inception_b3_7x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_1x7_3_inter_channel_buffer %d", uut.inception_b3_1x7_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_7x1_3_inter_channel_buffer %d", uut.inception_b3_7x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_concat_inception_channel_buffer_0 %d", uut.inception_b3_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_concat_inception_channel_buffer_1 %d", uut.inception_b3_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_concat_inception_channel_buffer_2 %d", uut.inception_b3_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b3_concat_inception_channel_buffer_3 %d", uut.inception_b3_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_pool_ave_inter_channel_buffer %d", uut.inception_b4_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_1x1_inter_channel_buffer %d", uut.inception_b4_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_1x1_2_inter_channel_buffer %d", uut.inception_b4_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_1x7_reduce_inter_channel_buffer %d", uut.inception_b4_1x7_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_1x7_inter_channel_buffer %d", uut.inception_b4_1x7_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_7x1_inter_channel_buffer %d", uut.inception_b4_7x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_1x7_2_reduce_inter_channel_buffer %d", uut.inception_b4_1x7_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_1x7_2_inter_channel_buffer %d", uut.inception_b4_1x7_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_7x1_2_inter_channel_buffer %d", uut.inception_b4_7x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_1x7_3_inter_channel_buffer %d", uut.inception_b4_1x7_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_7x1_3_inter_channel_buffer %d", uut.inception_b4_7x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_concat_inception_channel_buffer_0 %d", uut.inception_b4_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_concat_inception_channel_buffer_1 %d", uut.inception_b4_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_concat_inception_channel_buffer_2 %d", uut.inception_b4_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b4_concat_inception_channel_buffer_3 %d", uut.inception_b4_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_pool_ave_inter_channel_buffer %d", uut.inception_b5_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_1x1_inter_channel_buffer %d", uut.inception_b5_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_1x1_2_inter_channel_buffer %d", uut.inception_b5_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_1x7_reduce_inter_channel_buffer %d", uut.inception_b5_1x7_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_1x7_inter_channel_buffer %d", uut.inception_b5_1x7_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_7x1_inter_channel_buffer %d", uut.inception_b5_7x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_1x7_2_reduce_inter_channel_buffer %d", uut.inception_b5_1x7_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_1x7_2_inter_channel_buffer %d", uut.inception_b5_1x7_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_7x1_2_inter_channel_buffer %d", uut.inception_b5_7x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_1x7_3_inter_channel_buffer %d", uut.inception_b5_1x7_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_7x1_3_inter_channel_buffer %d", uut.inception_b5_7x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_concat_inception_channel_buffer_0 %d", uut.inception_b5_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_concat_inception_channel_buffer_1 %d", uut.inception_b5_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_concat_inception_channel_buffer_2 %d", uut.inception_b5_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b5_concat_inception_channel_buffer_3 %d", uut.inception_b5_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_pool_ave_inter_channel_buffer %d", uut.inception_b6_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_1x1_inter_channel_buffer %d", uut.inception_b6_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_1x1_2_inter_channel_buffer %d", uut.inception_b6_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_1x7_reduce_inter_channel_buffer %d", uut.inception_b6_1x7_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_1x7_inter_channel_buffer %d", uut.inception_b6_1x7_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_7x1_inter_channel_buffer %d", uut.inception_b6_7x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_1x7_2_reduce_inter_channel_buffer %d", uut.inception_b6_1x7_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_1x7_2_inter_channel_buffer %d", uut.inception_b6_1x7_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_7x1_2_inter_channel_buffer %d", uut.inception_b6_7x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_1x7_3_inter_channel_buffer %d", uut.inception_b6_1x7_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_7x1_3_inter_channel_buffer %d", uut.inception_b6_7x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_concat_inception_channel_buffer_0 %d", uut.inception_b6_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_concat_inception_channel_buffer_1 %d", uut.inception_b6_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_concat_inception_channel_buffer_2 %d", uut.inception_b6_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b6_concat_inception_channel_buffer_3 %d", uut.inception_b6_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_pool_ave_inter_channel_buffer %d", uut.inception_b7_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_1x1_inter_channel_buffer %d", uut.inception_b7_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_1x1_2_inter_channel_buffer %d", uut.inception_b7_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_1x7_reduce_inter_channel_buffer %d", uut.inception_b7_1x7_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_1x7_inter_channel_buffer %d", uut.inception_b7_1x7_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_7x1_inter_channel_buffer %d", uut.inception_b7_7x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_1x7_2_reduce_inter_channel_buffer %d", uut.inception_b7_1x7_2_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_1x7_2_inter_channel_buffer %d", uut.inception_b7_1x7_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_7x1_2_inter_channel_buffer %d", uut.inception_b7_7x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_1x7_3_inter_channel_buffer %d", uut.inception_b7_1x7_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_7x1_3_inter_channel_buffer %d", uut.inception_b7_7x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_concat_inception_channel_buffer_0 %d", uut.inception_b7_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_concat_inception_channel_buffer_1 %d", uut.inception_b7_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_concat_inception_channel_buffer_2 %d", uut.inception_b7_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_b7_concat_inception_channel_buffer_3 %d", uut.inception_b7_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_pool_inter_channel_buffer %d", uut.reduction_b_pool_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_3x3_reduce_inter_channel_buffer %d", uut.reduction_b_3x3_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_3x3_inter_channel_buffer %d", uut.reduction_b_3x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_1x7_reduce_inter_channel_buffer %d", uut.reduction_b_1x7_reduce_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_1x7_inter_channel_buffer %d", uut.reduction_b_1x7_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_7x1_inter_channel_buffer %d", uut.reduction_b_7x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_3x3_2_inter_channel_buffer %d", uut.reduction_b_3x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_concat_inception_channel_buffer_0 %d", uut.reduction_b_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_concat_inception_channel_buffer_1 %d", uut.reduction_b_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "reduction_b_concat_inception_channel_buffer_2 %d", uut.reduction_b_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_pool_ave_inter_channel_buffer %d", uut.inception_c1_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_1x1_inter_channel_buffer %d", uut.inception_c1_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_1x1_2_inter_channel_buffer %d", uut.inception_c1_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_1x1_3_inter_channel_buffer %d", uut.inception_c1_1x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_1x3_inter_channel_buffer %d", uut.inception_c1_1x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_3x1_inter_channel_buffer %d", uut.inception_c1_3x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_1x1_4_inter_channel_buffer %d", uut.inception_c1_1x1_4_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_1x3_2_inter_channel_buffer %d", uut.inception_c1_1x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_3x1_2_inter_channel_buffer %d", uut.inception_c1_3x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_1x3_3_inter_channel_buffer %d", uut.inception_c1_1x3_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_3x1_3_inter_channel_buffer %d", uut.inception_c1_3x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_concat_inception_channel_buffer_0 %d", uut.inception_c1_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_concat_inception_channel_buffer_1 %d", uut.inception_c1_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_concat_inception_channel_buffer_2 %d", uut.inception_c1_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_concat_inception_channel_buffer_3 %d", uut.inception_c1_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_concat_inception_channel_buffer_4 %d", uut.inception_c1_concat_inception_channel_buffer_4.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c1_concat_inception_channel_buffer_5 %d", uut.inception_c1_concat_inception_channel_buffer_5.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_pool_ave_inter_channel_buffer %d", uut.inception_c2_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_1x1_inter_channel_buffer %d", uut.inception_c2_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_1x1_2_inter_channel_buffer %d", uut.inception_c2_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_1x1_3_inter_channel_buffer %d", uut.inception_c2_1x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_1x3_inter_channel_buffer %d", uut.inception_c2_1x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_3x1_inter_channel_buffer %d", uut.inception_c2_3x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_1x1_4_inter_channel_buffer %d", uut.inception_c2_1x1_4_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_1x3_2_inter_channel_buffer %d", uut.inception_c2_1x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_3x1_2_inter_channel_buffer %d", uut.inception_c2_3x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_1x3_3_inter_channel_buffer %d", uut.inception_c2_1x3_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_3x1_3_inter_channel_buffer %d", uut.inception_c2_3x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_concat_inception_channel_buffer_0 %d", uut.inception_c2_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_concat_inception_channel_buffer_1 %d", uut.inception_c2_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_concat_inception_channel_buffer_2 %d", uut.inception_c2_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_concat_inception_channel_buffer_3 %d", uut.inception_c2_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_concat_inception_channel_buffer_4 %d", uut.inception_c2_concat_inception_channel_buffer_4.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c2_concat_inception_channel_buffer_5 %d", uut.inception_c2_concat_inception_channel_buffer_5.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_pool_ave_inter_channel_buffer %d", uut.inception_c3_pool_ave_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_1x1_inter_channel_buffer %d", uut.inception_c3_1x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_1x1_2_inter_channel_buffer %d", uut.inception_c3_1x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_1x1_3_inter_channel_buffer %d", uut.inception_c3_1x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_1x3_inter_channel_buffer %d", uut.inception_c3_1x3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_3x1_inter_channel_buffer %d", uut.inception_c3_3x1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_1x1_4_inter_channel_buffer %d", uut.inception_c3_1x1_4_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_1x3_2_inter_channel_buffer %d", uut.inception_c3_1x3_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_3x1_2_inter_channel_buffer %d", uut.inception_c3_3x1_2_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_1x3_3_inter_channel_buffer %d", uut.inception_c3_1x3_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_3x1_3_inter_channel_buffer %d", uut.inception_c3_3x1_3_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_concat_inception_channel_buffer_0 %d", uut.inception_c3_concat_inception_channel_buffer_0.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_concat_inception_channel_buffer_1 %d", uut.inception_c3_concat_inception_channel_buffer_1.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_concat_inception_channel_buffer_2 %d", uut.inception_c3_concat_inception_channel_buffer_2.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_concat_inception_channel_buffer_3 %d", uut.inception_c3_concat_inception_channel_buffer_3.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_concat_inception_channel_buffer_4 %d", uut.inception_c3_concat_inception_channel_buffer_4.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "inception_c3_concat_inception_channel_buffer_5 %d", uut.inception_c3_concat_inception_channel_buffer_5.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "pool_8x8_s1_inter_channel_buffer %d", uut.pool_8x8_s1_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fdisplay(fp, "classifier_inter_channel_buffer %d", uut.classifier_inter_channel_buffer.genblk1.fifo_sync_inst.fifo_max_depth);
	$fclose(fp);
	$finish;
end
endmodule
